---
title: "Exemplo 1 - Distribuição Beta"
author: "Aishameriane Schmidt"
date: "19 de agosto de 2017"
output: html_document
---

# Código antigo

Vamos utilizar a distribuição beta pois ela é conjugada da distribuição Bernoulli.

```{r}
require(ggplot2)
library(latex2exp)

x <- seq(0, 1, len = 100)

p <- qplot(x, geom = "blank")
stat1 <- stat_function(aes(x = x, y = ..y..), 
                       fun = dbeta, colour="red", 
                       n = 100, 
                       args = list(shape1 = .5, shape2 = .5))
p1 <- p + stat1 + ggtitle(TeX("$\\alpha = \\beta = .5$"))

p <- qplot(x, geom = "blank")
stat2 <- stat_function(aes(x = x, y = ..y..), 
                       fun = dbeta, colour="red", 
                       n = 100, 
                       args = list(shape1 = 1, shape2 = 1))
p2 <- p + stat2+ ggtitle(TeX("$\\alpha = \\beta = 1$"))

p <- qplot(x, geom = "blank")
stat3 <- stat_function(aes(x = x, y = ..y..), 
                       fun = dbeta, colour="red", 
                       n = 100, 
                       args = list(shape1 = 10, shape2 = 10))
p3 <- p + stat3+ ggtitle(TeX("$\\alpha = \\beta = 10$"))

p <- qplot(x, geom = "blank")

stat4 <- stat_function(aes(x = x, y = ..y..), 
                       fun = dbeta, colour="red", 
                       n = 100, 
                       args = list(shape1 = 5, shape2 = 2))
p4 <- p + stat4+ ggtitle(TeX("$\\alpha = 5,\\beta = 2$"))

# Multiple plot function
#
# ggplot objects can be passed in ..., or to plotlist (as a list of ggplot objects)
# - cols:   Number of columns in layout
# - layout: A matrix specifying the layout. If present, 'cols' is ignored.
#
# If the layout is something like matrix(c(1,2,3,3), nrow=2, byrow=TRUE),
# then plot 1 will go in the upper left, 2 will go in the upper right, and
# 3 will go all the way across the bottom.
#
multiplot <- function(..., plotlist=NULL, file, cols=1, layout=NULL) {
  library(grid)

  # Make a list from the ... arguments and plotlist
  plots <- c(list(...), plotlist)

  numPlots = length(plots)

  # If layout is NULL, then use 'cols' to determine layout
  if (is.null(layout)) {
    # Make the panel
    # ncol: Number of columns of plots
    # nrow: Number of rows needed, calculated from # of cols
    layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                    ncol = cols, nrow = ceiling(numPlots/cols))
  }

 if (numPlots==1) {
    print(plots[[1]])

  } else {
    # Set up the page
    grid.newpage()
    pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))

    # Make each plot, in the correct location
    for (i in 1:numPlots) {
      # Get the i,j matrix positions of the regions that contain this subplot
      matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))

      print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                      layout.pos.col = matchidx$col))
    }
  }
}

multiplot(p1, p2, p3, p4, cols=2)
```

Salva a figura em PDF:

```{r, eval = FALSE}
pdf(file="C:\\Users\\Aishameriane\\OneDrive\\Documentos\\Mestrado Economia\\Bayesiana - 2017-01\\Imagens notas de aula\\beta.pdf")
multiplot(p1, p2, p3, p4, cols=2)
dev.off()
```


# Código novo

```{r, warning = FALSE}
# Verificando dependências dos pacotes
list.of.packages <- c("ggplot2")
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages)

library(ggplot2)

p <- ggplot(data.frame(x = c(0,1)), aes(x=x)) + 
     stat_function(fun = dbeta, args = list(.5, .5), 
                   aes(colour = "Alpha = .5, Beta = .5"), size = 1) +
     stat_function(fun = dbeta, args = list(1, 1), 
                   aes(colour = "Alpha = 1, Beta = 1"), size = 1) +
     stat_function(fun = dbeta, args = list(10, 10), 
                   aes(colour = "Alpha = 10, Beta = 10"), size = 1) +
     stat_function(fun = dbeta, args = list(5, 2), 
                   aes(colour = "Alpha = 5, Beta = 2"), size = 1) +
     
     scale_x_continuous(name = "Valores de X",
                        breaks = seq(0, 1, 0.2),
                        limits = c(0,1)) +
     scale_y_continuous(name = "Densidade") + 
  
     ggtitle("") +
        scale_colour_brewer(palette="Dark2") +
        labs(colour = "Parâmetros")

p <- p + theme_bw()
p
```

Salva a figura em PDF:

```{r, eval = FALSE}
# Altura e largura são em inches, default = 7
pdf(file="C:\\Users\\Aishameriane\\Dropbox\\TCC Aisha\\Texto TCC\\TCC\\Figuras\\Fig-1.001.pdf", width = 6, height = 3)
p
dev.off()
```
# Triplot

```{r}
library(LearnBayes)
library(pscl)
library(ggplot2)
library(reshape2)
library(latex2exp)

# Cria um vetor de thetas
theta  <- seq(0, 1, length = 100)

# Priori
alphapriori <- 10
betapriori <- 10
priori <- dbeta(theta, alphapriori, betapriori)
#qplot(theta, priori, geom = "line")

# Número de caras observadas
somay <- 75
# Tamanho da amostra
n <- 100
# Verossimilhança - o termo (n+1) é multiplicado para dar escala
vero <- (n+1)*(factorial(n)/(factorial(somay)*factorial(n-somay)))*theta^somay*(1-theta)^(n-somay)
#qplot(theta, vero, geom="line")

# Posteriori
alphapost <- alphapriori + somay
betapost <- betapriori + n - somay
post <- dbeta(theta, alphapost, betapost)
#qplot(theta, post, geom="line")

# Juntando os dados
df <- as.data.frame(cbind(theta, priori, vero, post))
df <- melt(df, theta)
levels(df$variable)[levels(df$variable) == "priori"] <- "Priori"
levels(df$variable)[levels(df$variable) == "vero"]   <- "Verossimilhança"
levels(df$variable)[levels(df$variable) == "post"]   <- "Posteriori"
head(df)

p <- ggplot(df, aes(theta,value, color = factor(variable))) +
  geom_line(size = 1)+
  scale_x_continuous(name = TeX("$\\theta$")) +
     scale_y_continuous(name = "") + 
  ggtitle("") +
    scale_colour_brewer(palette="Dark2") +
    labs(colour = "Função") +
  theme_bw()
#p <- p + theme(legend.position="top")
p

# Altura e largura são em inches, default = 7
#pdf(file="C:\\Users\\Aishameriane\\Dropbox\\TCC Aisha\\Texto TCC\\TCC\\Figuras\\Fig-1.003.pdf", width = 6, height = 3)
#p
#dev.off()

```